name: Auto Build ImmortalWrt NanoPi R2S

on:
  schedule:
    - cron: '0 4 * * *'   # 每天 04:00 UTC 检查一次更新
  workflow_dispatch:       # 支持手动触发

jobs:
  auto-build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout workflow repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential git wget curl unzip \
            libncurses5-dev libncursesw5-dev zlib1g-dev gawk \
            flex gettext libssl-dev python3-distutils rsync

      - name: Clone ImmortalWrt
        run: |
          git clone https://github.com/immortalwrt/immortalwrt.git immortalwrt
          cd immortalwrt
          git fetch --all
          git checkout openwrt-24.10   # 可以改成 23.05 或其他分支
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Add R2S boot patch
        run: |
          cd immortalwrt
          mkdir -p target/linux/rockchip/patches-6.1
          cat > target/linux/rockchip/patches-6.1/999-fix-r2s-sdmmc.patch << "EOF"
--- a/arch/arm/dts/rk3328-nanopi-r2s.dts
+++ b/arch/arm/dts/rk3328-nanopi-r2s.dts
@@ -55,6 +55,15 @@
        };
 };

+&sdmmc {
+       bus-width = <4>;
+       cap-sd-highspeed;
+       supports-sd;
+       pinctrl-names = "default";
+       pinctrl-0 = <&sdmmc0m1_gpio>;
+       vmmc-supply = <&vcc_io_sdio>;
+       status = "okay";
+};
EOF

      - name: Configure NanoPi R2S
        run: |
          cd immortalwrt
          make defconfig
          sed -i 's/CONFIG_TARGET_MULTI_PROFILE=y/# CONFIG_TARGET_MULTI_PROFILE is not set/' .config
          echo "CONFIG_TARGET_rockchip=y" >> .config
          echo "CONFIG_TARGET_rockchip_rk3328=y" >> .config
          echo "CONFIG_TARGET_rockchip_rk3328_DEVICE_friendlyarm_nanopi-r2s=y" >> .config

      - name: Build firmware
        run: |
          cd immortalwrt
          make -j$(nproc) || make -j1 V=s

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: immortalwrt-nanopi-r2s
          path: immortalwrt/bin/targets/rockchip/armv8/*
